/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class Lesehan extends javax.swing.JFrame {

    /**
     * Creates new form Lesehan
     */
    public Lesehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxnasikucing = new javax.swing.JCheckBox();
        cbxnasigoreng = new javax.swing.JCheckBox();
        cbxsosisbakar = new javax.swing.JCheckBox();
        cbxbaksobakar = new javax.swing.JCheckBox();
        cbxesteh = new javax.swing.JCheckBox();
        cbxjusjeruk = new javax.swing.JCheckBox();
        cbxjosua = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtjumlah1 = new javax.swing.JTextField();
        txtjumlah2 = new javax.swing.JTextField();
        txtjumlah3 = new javax.swing.JTextField();
        txtjumlah4 = new javax.swing.JTextField();
        txtjumlah5 = new javax.swing.JTextField();
        txtjumlah6 = new javax.swing.JTextField();
        txtjumlah7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txapesan = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Makanan:");

        jLabel2.setText("Harga:");

        jLabel3.setText("Jumlah:");

        jLabel4.setText("Menu Minuman:");

        jLabel5.setText("Harga:");

        jLabel6.setText("Jumlah:");

        cbxnasikucing.setText("Nasi Kucing");
        cbxnasikucing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnasikucingActionPerformed(evt);
            }
        });

        cbxnasigoreng.setText("Nasi Goreng");
        cbxnasigoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnasigorengActionPerformed(evt);
            }
        });

        cbxsosisbakar.setText("Sosis Bakar");

        cbxbaksobakar.setText("Bakso Bakar");
        cbxbaksobakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxbaksobakarActionPerformed(evt);
            }
        });

        cbxesteh.setText("Es Teh");
        cbxesteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxestehActionPerformed(evt);
            }
        });

        cbxjusjeruk.setText("Jus Jeruk");

        cbxjosua.setText("Josua");
        cbxjosua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxjosuaActionPerformed(evt);
            }
        });

        jLabel7.setText("Rp.10000");

        jLabel8.setText("Rp.12000");

        jLabel9.setText("Rp.5000");

        jLabel10.setText("Rp.5000");

        jLabel11.setText("Rp.3000");

        jLabel12.setText("Rp.5000");

        jLabel13.setText("Rp.5000");

        txtjumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah1ActionPerformed(evt);
            }
        });

        txtjumlah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah2ActionPerformed(evt);
            }
        });

        txtjumlah6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah6ActionPerformed(evt);
            }
        });

        txtjumlah7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah7ActionPerformed(evt);
            }
        });

        jLabel14.setText("Yang di Pesan :");

        txapesan.setColumns(20);
        txapesan.setRows(5);
        jScrollPane1.setViewportView(txapesan);

        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxnasigoreng)
                            .addComponent(jLabel1)
                            .addComponent(cbxsosisbakar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxbaksobakar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxnasikucing, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtjumlah1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(txtjumlah2)
                                            .addComponent(txtjumlah3)
                                            .addComponent(txtjumlah4))))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cbxesteh)
                                    .addComponent(cbxjusjeruk)
                                    .addComponent(cbxjosua))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addComponent(jLabel13))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(txtjumlah5)
                                    .addComponent(txtjumlah6)
                                    .addComponent(txtjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnpesan)
                .addGap(170, 170, 170)
                .addComponent(btnreset)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxnasikucing)
                    .addComponent(cbxesteh)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(txtjumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxnasigoreng)
                    .addComponent(cbxjusjeruk)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(txtjumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxsosisbakar)
                    .addComponent(cbxjosua)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(txtjumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxbaksobakar)
                    .addComponent(jLabel10)
                    .addComponent(txtjumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpesan)
                    .addComponent(btnreset))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxnasikucingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnasikucingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxnasikucingActionPerformed

    private void cbxnasigorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnasigorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxnasigorengActionPerformed

    private void cbxbaksobakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxbaksobakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxbaksobakarActionPerformed

    private void cbxestehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxestehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxestehActionPerformed

    private void cbxjosuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxjosuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxjosuaActionPerformed

    private void txtjumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah1ActionPerformed

    private void txtjumlah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah2ActionPerformed

    private void txtjumlah6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah6ActionPerformed

    private void txtjumlah7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah7ActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        String tampil;
        tampil = "";
        int bayar = 0;
        if (cbxnasikucing.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah1.getText());
            int total;
            total=jumlah*100000;
            bayar=bayar+total;
            tampil+=cbxnasikucing.getText()+" Rp.100000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxnasigoreng.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah2.getText());
            int total;
            total=jumlah*12000;
            bayar=bayar+total;
            tampil+=cbxnasigoreng.getText()+" Rp.12000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxsosisbakar.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah3.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil+=cbxsosisbakar.getText()+" Rp.5000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxbaksobakar.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah4.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil+=cbxbaksobakar.getText()+" Rp.5000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxesteh.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah7.getText());
            int total;
            total=jumlah*3000;
            bayar=bayar+total;
            tampil+=cbxesteh.getText()+" Rp.3000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxjusjeruk.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah6.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil+=cbxjusjeruk.getText()+" Rp.5000"+" x "+jumlah+" = "+total+"\n";
        } if (cbxjosua.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah5.getText());
            int total;
            total=jumlah*5000;
            bayar=bayar+total;
            tampil+=cbxjosua.getText()+" Rp.5000"+" x "+jumlah+" = "+total+"\n";
            txapesan.setText(tampil+"=========================="+"\n"+"Total Bayar ="+bayar);
        }    

            
    }//GEN-LAST:event_btnpesanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lesehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lesehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lesehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lesehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lesehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox cbxbaksobakar;
    private javax.swing.JCheckBox cbxesteh;
    private javax.swing.JCheckBox cbxjosua;
    private javax.swing.JCheckBox cbxjusjeruk;
    private javax.swing.JCheckBox cbxnasigoreng;
    private javax.swing.JCheckBox cbxnasikucing;
    private javax.swing.JCheckBox cbxsosisbakar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txapesan;
    private javax.swing.JTextField txtjumlah1;
    private javax.swing.JTextField txtjumlah2;
    private javax.swing.JTextField txtjumlah3;
    private javax.swing.JTextField txtjumlah4;
    private javax.swing.JTextField txtjumlah5;
    private javax.swing.JTextField txtjumlah6;
    private javax.swing.JTextField txtjumlah7;
    // End of variables declaration//GEN-END:variables
}
